# Generated by Django 3.2.19 on 2023-09-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0002_auto_20230914_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUsers',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RESTAPI.users')),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.application')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('RESTAPI.users',),
        ),
    ]
