# Generated by Django 3.2.19 on 2023-09-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0004_remove_packages_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
