# Generated by Django 3.2.21 on 2023-09-14 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0005_auto_20230914_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.CharField(default='blah blah', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='applicationLogo'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.application'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.packages'),
        ),
    ]
