# Generated by Django 3.2.21 on 2023-09-14 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0006_auto_20230914_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
